"""Add tenant_id to llm_providers

Revision ID: c7e4a55b3f7c
Revises: f0e3c2eeb396
Create Date: 2025-10-05 20:07:02.394522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e4a55b3f7c'
down_revision: Union[str, Sequence[str], None] = 'f0e3c2eeb396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_llm_providers_tenant_id'), 'llm_providers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'llm_providers', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_providers', type_='foreignkey')
    op.drop_index(op.f('ix_llm_providers_tenant_id'), table_name='llm_providers')
    op.drop_column('llm_providers', 'tenant_id')
    # ### end Alembic commands ###
