"""Add CrewAI agent fields

Revision ID: f0e3c2eeb396
Revises: a411975fd9b6
Create Date: 2025-10-05 18:49:12.644798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e3c2eeb396'
down_revision: Union[str, Sequence[str], None] = 'a411975fd9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('cache', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('max_iter', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('max_rpm', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('max_execution_time', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('allow_code_execution', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('respect_context_window', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('max_retry_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_retry_limit')
    op.drop_column('agents', 'respect_context_window')
    op.drop_column('agents', 'allow_code_execution')
    op.drop_column('agents', 'max_execution_time')
    op.drop_column('agents', 'max_rpm')
    op.drop_column('agents', 'max_iter')
    op.drop_column('agents', 'cache')
    # ### end Alembic commands ###
