apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.crewai-platform.com"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://api.crewai-platform.com"
        - name: NEXT_PUBLIC_ENABLE_ANALYTICS
          value: "true"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
