apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crewai-prod

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

# Production replicas (as defined in base HPA)
# No replica override - use base deployment values

# Production-specific config
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=WARNING
  - ENABLE_MONITORING=true
  - ENABLE_TRACING=true

# Production images with specific tags
images:
- name: crewai-backend
  newName: gcr.io/crewai-project/backend
  newTag: v1.0.0  # Use semantic versioning in prod
- name: crewai-frontend
  newName: gcr.io/crewai-project/frontend
  newTag: v1.0.0

patchesStrategicMerge:
- backend-prod-patch.yaml
- frontend-prod-patch.yaml
