apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crewai-staging

bases:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging

# Staging replicas
replicas:
- name: backend
  count: 2
- name: frontend
  count: 2
- name: docker-dind
  count: 2

# Staging-specific config
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=INFO

# Staging images
images:
- name: crewai-backend
  newName: gcr.io/crewai-project/backend
  newTag: staging
- name: crewai-frontend
  newName: gcr.io/crewai-project/frontend
  newTag: staging

patchesStrategicMerge:
- ingress-patch.yaml
